# Railway Configuration
# This file is automatically detected by Railway

# Build settings
[build]
builder = "dockerfile"

# Runtime settings  
[deploy]
healthcheckPath = "/_stcore/health"

# Environment variables
[env]
PYTHONPATH = "/app/src"
