services:
  - type: web
    name: 2d-fea-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHONPATH
        value: /app/src
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    buildCommand: ""
    startCommand: streamlit run src/web_app_clean.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
