name: Build Windows Executables

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 🔽 Checkout Repository
      uses: actions/checkout@v4
    
    - name: 🐍 Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    
    - name: 📋 Display Python Info
      run: |
        python --version
        python -m pip --version
        echo "Architecture: x64"
    
    - name: 🔧 Install System Dependencies
      run: |
        # Update pip and install wheel
        python -m pip install --upgrade pip wheel setuptools
    
    - name: 📦 Install Python Dependencies
      run: |
        # Install core dependencies
        pip install numpy matplotlib scipy plotly
        pip install PySide6 pyinstaller
        pip install gmsh meshio h5py
        
        # Install additional requirements if they exist
        if (Test-Path "requirements_windows.txt") {
          pip install -r requirements_windows.txt
        } elseif (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        }
    
    - name: 🔍 Verify Installation
      run: |
        python -c "import sys; print('Python:', sys.version)"
        python -c "import numpy; print('NumPy:', numpy.__version__)"
        python -c "import matplotlib; print('Matplotlib:', matplotlib.__version__)"
        python -c "import PySide6; print('PySide6:', PySide6.__version__)"
        python -c "import PyInstaller; print('PyInstaller:', PyInstaller.__version__)"
        python -c "import gmsh; print('GMSH available')"
        python -c "import meshio; print('MeshIO:', meshio.__version__)"
        python -c "import h5py; print('h5py:', h5py.__version__)"
    
    - name: 🏗️ Create Build Directories
      run: |
        New-Item -ItemType Directory -Force -Path "dist"
        New-Item -ItemType Directory -Force -Path "build"
    
    - name: 📝 Create PyInstaller Spec Files
      run: |
        # Create spec file for main GUI application
        $mainSpec = @"
        # -*- mode: python ; coding: utf-8 -*-
        import sys
        import os
        from PyInstaller.utils.hooks import collect_data_files, collect_submodules

        # Collect data files for various packages
        datas = []
        datas += collect_data_files('matplotlib')
        datas += collect_data_files('PySide6')

        # Hidden imports for dependencies
        hiddenimports = []
        hiddenimports += collect_submodules('matplotlib')
        hiddenimports += collect_submodules('PySide6')
        hiddenimports += ['numpy', 'scipy', 'json', 'pathlib', 'gmsh', 'meshio', 'h5py']

        block_cipher = None

        a = Analysis(
            ['src/main_windows.py'],
            pathex=[],
            binaries=[],
            datas=datas,
            hiddenimports=hiddenimports,
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=['tkinter', 'test', 'unittest'],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name='2D_FEA_Windows',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=False,
            disable_windowed_traceback=False,
            target_arch='x64',
            codesign_identity=None,
            entitlements_file=None,
            icon=None,
        )
        "@
        $mainSpec | Out-File -FilePath "build_windows.spec" -Encoding UTF8
    
    - name: 🔨 Build Windows Application
      run: |
        echo "Building 2D FEA Windows application..."
        pyinstaller build_windows.spec --clean --noconfirm
        if (Test-Path "dist/2D_FEA_Windows.exe") {
          echo "✅ Application built successfully"
          Get-Item "dist/2D_FEA_Windows.exe" | Format-List Name, Length, LastWriteTime
        } else {
          echo "❌ Application build failed"
          Get-ChildItem "dist/" -ErrorAction SilentlyContinue
          exit 1
        }
    
    - name: 🧪 Test Executable
      run: |
        echo "Testing executable..."
        if (Test-Path "dist/2D_FEA_Windows.exe") {
          $file = Get-Item "dist/2D_FEA_Windows.exe"
          echo "2D_FEA_Windows.exe: $($file.Length) bytes"
          
          # Quick execution test (should not crash immediately)
          echo "Quick startup test..."
          try {
            $process = Start-Process "dist/2D_FEA_Windows.exe" -ArgumentList "--version" -PassThru -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue
            echo "App exit code: $($process.ExitCode)"
          } catch {
            echo "App test completed (expected for GUI app)"
          }
        } else {
          echo "❌ Executable not found"
          exit 1
        }
    
    - name: 📦 Create Distribution Package
      run: |
        echo "Creating distribution package..."
        
        # Create distribution folder
        $distFolder = "2D_FEA_Windows_3.12_x64"
        New-Item -ItemType Directory -Force -Path $distFolder
        
        # Copy executable
        if (Test-Path "dist/2D_FEA_Windows.exe") {
          Copy-Item "dist/2D_FEA_Windows.exe" "$distFolder/"
        }
        
        # Create README for distribution
        $readme = @"
        # 2D FEA Windows Application
        
        Built on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        Python Version: 3.12
        Architecture: x64
        
        ## Application:
        
        - **2D_FEA_Windows.exe**: 2D Finite Element Analysis application with GUI
        
        ## System Requirements:
        
        - Windows 10/11 (64-bit)
        - No additional installation required
        - All dependencies are bundled
        
        ## Usage:
        
        1. Double-click 2D_FEA_Windows.exe
        2. The application will start with a GUI interface
        3. Follow the on-screen instructions for torsion analysis
        
        ## Features:
        
        - Geometry input and visualization
        - Mesh generation with GMSH
        - Save/Load project files
        - Results visualization with matplotlib
        
        ## Troubleshooting:
        
        - If Windows shows a security warning, click "More info" then "Run anyway"
        - Ensure Windows Defender is not blocking the executable
        - Run as Administrator if file access issues occur
        
        ## Build Information:
        
        - Built with PyInstaller
        - Includes PySide6, matplotlib, numpy, GMSH, meshio
        - Self-contained executable (no Python installation required)
        
        For support, visit: https://github.com/YachtEngineeringservices/2d-FEA
        "@
        $readme | Out-File -FilePath "$distFolder/README.txt" -Encoding UTF8
        
        # Create ZIP package
        Compress-Archive -Path "$distFolder/*" -DestinationPath "$distFolder.zip" -Force
        
        echo "Distribution package created: $distFolder.zip"
        Get-Item "$distFolder.zip" | Format-List Name, Length
    
    - name: 📊 Build Summary
      run: |
        echo "=== BUILD SUMMARY ==="
        echo "Python Version: 3.12"
        echo "Architecture: x64"
        echo "Build Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        echo ""
        echo "Built Application:"
        if (Test-Path "dist/2D_FEA_Windows.exe") {
          $size = (Get-Item "dist/2D_FEA_Windows.exe").Length / 1MB
          echo "✅ 2D_FEA_Windows.exe ({0:N1} MB)" -f $size
        }
        echo ""
        echo "Distribution Packages:"
        Get-ChildItem -Filter "*.zip" | ForEach-Object {
          $sizeMB = $_.Length / 1MB
          echo "📦 $($_.Name) ({0:N1} MB)" -f $sizeMB
        }
    
    - name: 📤 Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 2D-FEA-Windows-Python3.12-x64
        path: |
          dist/*.exe
          *.zip
          build/*.spec
        retention-days: 30
    
    - name: 📤 Upload Distribution ZIP
      uses: actions/upload-artifact@v4
      with:
        name: 2D-FEA-Windows-Distribution-Python3.12
        path: "*.zip"
        retention-days: 90

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: 🔽 Download All Artifacts
      uses: actions/download-artifact@v4
    
    - name: 📦 Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.zip
          **/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
