[global]

# Development settings
developmentMode = false

# General settings
showWarningOnDirectExecution = false

# Browser settings
showErrorDetails = true

[logger]

# Logger settings
level = "info"

[client]

# Show file watcher information in the sidebar
showSidebarNavigation = true

# Toolbar mode
toolbarMode = "minimal"

[server]

# Server settings
headless = true
enableCORS = false
enableXsrfProtection = true

# File watching
enableWebsocketCompression = false

[theme]

# Theme settings for professional appearance
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
